CREATE TABLE "Config" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "Key" TEXT NOT NULL, "Value" TEXT NOT NULL);
CREATE TABLE sqlite_sequence(name,seq);
CREATE UNIQUE INDEX "IX_Config_Key" ON "Config" ("Key" ASC);
CREATE TABLE "RootFolders" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "Path" TEXT NOT NULL);
CREATE UNIQUE INDEX "IX_RootFolders_Path" ON "RootFolders" ("Path" ASC);
CREATE TABLE "QualityDefinitions" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "Quality" INTEGER NOT NULL, "Title" TEXT NOT NULL, "MinSize" NUMERIC, "MaxSize" NUMERIC, "PreferredSize" NUMERIC);
CREATE UNIQUE INDEX "IX_QualityDefinitions_Quality" ON "QualityDefinitions" ("Quality" ASC);
CREATE UNIQUE INDEX "IX_QualityDefinitions_Title" ON "QualityDefinitions" ("Title" ASC);
CREATE TABLE "Metadata" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "Enable" INTEGER NOT NULL, "Name" TEXT NOT NULL, "Implementation" TEXT NOT NULL, "Settings" TEXT NOT NULL, "ConfigContract" TEXT NOT NULL);
CREATE TABLE "DownloadClients" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "Enable" INTEGER NOT NULL, "Name" TEXT NOT NULL, "Implementation" TEXT NOT NULL, "Settings" TEXT NOT NULL, "ConfigContract" TEXT NOT NULL, "Priority" INTEGER NOT NULL DEFAULT 1, "RemoveCompletedDownloads" INTEGER NOT NULL DEFAULT 1, "RemoveFailedDownloads" INTEGER NOT NULL DEFAULT 1, "Tags" TEXT);
CREATE TABLE "RemotePathMappings" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "Host" TEXT NOT NULL, "RemotePath" TEXT NOT NULL, "LocalPath" TEXT NOT NULL);
CREATE TABLE "Tags" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "Label" TEXT NOT NULL);
CREATE UNIQUE INDEX "IX_Tags_Label" ON "Tags" ("Label" ASC);
CREATE TABLE "DelayProfiles" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "EnableUsenet" INTEGER NOT NULL, "EnableTorrent" INTEGER NOT NULL, "PreferredProtocol" INTEGER NOT NULL, "UsenetDelay" INTEGER NOT NULL, "TorrentDelay" INTEGER NOT NULL, "Order" INTEGER NOT NULL, "Tags" TEXT NOT NULL, "BypassIfHighestQuality" INTEGER NOT NULL DEFAULT 0, "BypassIfAboveCustomFormatScore" INTEGER NOT NULL DEFAULT 0, "MinimumCustomFormatScore" INTEGER);
CREATE TABLE "Users" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "Identifier" TEXT NOT NULL, "Username" TEXT NOT NULL, "Password" TEXT NOT NULL, "Salt" TEXT, "Iterations" INTEGER);
CREATE UNIQUE INDEX "IX_Users_Identifier" ON "Users" ("Identifier" ASC);
CREATE UNIQUE INDEX "IX_Users_Username" ON "Users" ("Username" ASC);
CREATE TABLE "ImportExclusions" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "TmdbId" INTEGER NOT NULL, "MovieTitle" TEXT, "MovieYear" INTEGER DEFAULT 0);
CREATE UNIQUE INDEX "IX_ImportExclusions_TmdbId" ON "ImportExclusions" ("TmdbId" ASC);
CREATE TABLE "CustomFilters" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "Type" TEXT NOT NULL, "Label" TEXT NOT NULL, "Filters" TEXT NOT NULL);
CREATE TABLE "Indexers" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "Name" TEXT NOT NULL, "Implementation" TEXT NOT NULL, "Settings" TEXT, "ConfigContract" TEXT, "EnableRss" INTEGER, "EnableAutomaticSearch" INTEGER, "EnableInteractiveSearch" INTEGER NOT NULL, "Priority" INTEGER NOT NULL DEFAULT 25, "Tags" TEXT, "DownloadClientId" INTEGER NOT NULL DEFAULT 0);
CREATE UNIQUE INDEX "IX_Indexers_Name" ON "Indexers" ("Name" ASC);
CREATE TABLE "Notifications" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "Name" TEXT NOT NULL, "OnGrab" INTEGER NOT NULL, "OnDownload" INTEGER NOT NULL, "Settings" TEXT NOT NULL, "Implementation" TEXT NOT NULL, "ConfigContract" TEXT, "OnUpgrade" INTEGER, "Tags" TEXT, "OnRename" INTEGER NOT NULL, "OnHealthIssue" INTEGER NOT NULL, "IncludeHealthWarnings" INTEGER NOT NULL, "OnMovieDelete" INTEGER NOT NULL, "OnMovieFileDelete" INTEGER NOT NULL DEFAULT 0, "OnMovieFileDeleteForUpgrade" INTEGER NOT NULL DEFAULT 0, "OnApplicationUpdate" INTEGER NOT NULL DEFAULT 0, "OnMovieAdded" INTEGER NOT NULL DEFAULT 0, "OnHealthRestored" INTEGER NOT NULL DEFAULT 0, "OnManualInteractionRequired" INTEGER NOT NULL DEFAULT 0);
CREATE TABLE "QualityProfiles" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "Name" TEXT NOT NULL, "Cutoff" INTEGER NOT NULL, "Items" TEXT NOT NULL, "Language" INTEGER, "FormatItems" TEXT NOT NULL, "UpgradeAllowed" INTEGER, "MinFormatScore" INTEGER NOT NULL, "CutoffFormatScore" INTEGER NOT NULL, "MinUpgradeFormatScore" INTEGER NOT NULL DEFAULT 1);
CREATE UNIQUE INDEX "IX_Profiles_Name" ON "QualityProfiles" ("Name" ASC);
CREATE TABLE "NamingConfig" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "MultiEpisodeStyle" INTEGER NOT NULL, "ReplaceIllegalCharacters" INTEGER NOT NULL, "StandardMovieFormat" TEXT, "MovieFolderFormat" TEXT, "ColonReplacementFormat" INTEGER NOT NULL, "RenameMovies" INTEGER NOT NULL);
CREATE TABLE "CustomFormats" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "Name" TEXT NOT NULL, "Specifications" TEXT NOT NULL, "IncludeCustomFormatWhenRenaming" INTEGER NOT NULL);
CREATE UNIQUE INDEX "IX_CustomFormats_Name" ON "CustomFormats" ("Name" ASC);
CREATE TABLE "Credits" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "CreditTmdbId" TEXT NOT NULL, "PersonTmdbId" INTEGER NOT NULL, "Name" TEXT NOT NULL, "Images" TEXT NOT NULL, "Character" TEXT, "Order" INTEGER NOT NULL, "Job" TEXT, "Department" TEXT, "Type" INTEGER NOT NULL, "MovieMetadataId" INTEGER NOT NULL);
CREATE UNIQUE INDEX "IX_Credits_CreditTmdbId" ON "Credits" ("CreditTmdbId" ASC);
CREATE TABLE "MovieTranslations" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "Title" TEXT, "CleanTitle" TEXT, "Overview" TEXT, "Language" INTEGER NOT NULL, "MovieMetadataId" INTEGER NOT NULL);
CREATE INDEX "IX_MovieTranslations_Language" ON "MovieTranslations" ("Language" ASC);
CREATE INDEX "IX_MovieTranslations_CleanTitle" ON "MovieTranslations" ("CleanTitle" ASC);
CREATE TABLE "ImportListMovies" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "ListId" INTEGER NOT NULL, "MovieMetadataId" INTEGER NOT NULL);
CREATE INDEX "IX_ImportListMovies_MovieMetadataId" ON "ImportListMovies" ("MovieMetadataId" ASC);
CREATE INDEX "IX_MovieTranslations_MovieMetadataId" ON "MovieTranslations" ("MovieMetadataId" ASC);
CREATE INDEX "IX_Credits_MovieMetadataId" ON "Credits" ("MovieMetadataId" ASC);
CREATE TABLE "Blocklist" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "SourceTitle" TEXT NOT NULL, "Quality" TEXT NOT NULL, "Date" DATETIME NOT NULL, "PublishedDate" DATETIME, "Size" INTEGER, "Protocol" INTEGER, "Indexer" TEXT, "Message" TEXT, "TorrentInfoHash" TEXT, "MovieId" INTEGER, "Languages" TEXT NOT NULL, "IndexerFlags" INTEGER NOT NULL);
CREATE TABLE "Collections" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "TmdbId" INTEGER NOT NULL, "QualityProfileId" INTEGER NOT NULL, "RootFolderPath" TEXT NOT NULL, "MinimumAvailability" INTEGER NOT NULL, "SearchOnAdd" INTEGER NOT NULL, "Title" TEXT NOT NULL, "SortTitle" TEXT, "CleanTitle" TEXT NOT NULL, "Overview" TEXT, "Images" TEXT NOT NULL, "Monitored" INTEGER NOT NULL, "LastInfoSync" DATETIME, "Added" DATETIME, "Tags" TEXT);
CREATE UNIQUE INDEX "IX_Collections_TmdbId" ON "Collections" ("TmdbId" ASC);
CREATE TABLE "Commands" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "Name" TEXT NOT NULL, "Body" TEXT NOT NULL, "Priority" INTEGER NOT NULL, "Status" INTEGER NOT NULL, "QueuedAt" DATETIME NOT NULL, "StartedAt" DATETIME, "EndedAt" DATETIME, "Duration" TEXT, "Exception" TEXT, "Trigger" INTEGER NOT NULL, "Result" INTEGER NOT NULL DEFAULT 1);
CREATE TABLE "DownloadClientStatus" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "ProviderId" INTEGER NOT NULL, "InitialFailure" DATETIME, "MostRecentFailure" DATETIME, "EscalationLevel" INTEGER NOT NULL, "DisabledTill" DATETIME);
CREATE UNIQUE INDEX "IX_DownloadClientStatus_ProviderId" ON "DownloadClientStatus" ("ProviderId" ASC);
CREATE TABLE "DownloadHistory" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "EventType" INTEGER NOT NULL, "MovieId" INTEGER NOT NULL, "DownloadId" TEXT NOT NULL, "SourceTitle" TEXT NOT NULL, "Date" DATETIME NOT NULL, "Protocol" INTEGER, "IndexerId" INTEGER, "DownloadClientId" INTEGER, "Release" TEXT, "Data" TEXT);
CREATE INDEX "IX_DownloadHistory_EventType" ON "DownloadHistory" ("EventType" ASC);
CREATE INDEX "IX_DownloadHistory_MovieId" ON "DownloadHistory" ("MovieId" ASC);
CREATE INDEX "IX_DownloadHistory_DownloadId" ON "DownloadHistory" ("DownloadId" ASC);
CREATE TABLE "ExtraFiles" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "MovieId" INTEGER NOT NULL, "MovieFileId" INTEGER NOT NULL, "RelativePath" TEXT NOT NULL, "Extension" TEXT NOT NULL, "Added" DATETIME NOT NULL, "LastUpdated" DATETIME NOT NULL);
CREATE TABLE "History" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "SourceTitle" TEXT NOT NULL, "Date" DATETIME NOT NULL, "Quality" TEXT NOT NULL, "Data" TEXT NOT NULL, "EventType" INTEGER, "DownloadId" TEXT, "MovieId" INTEGER NOT NULL, "Languages" TEXT NOT NULL);
CREATE INDEX "IX_History_Date" ON "History" ("Date" ASC);
CREATE TABLE "IndexerStatus" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "ProviderId" INTEGER NOT NULL, "InitialFailure" DATETIME, "MostRecentFailure" DATETIME, "EscalationLevel" INTEGER NOT NULL, "DisabledTill" DATETIME, "LastRssSyncReleaseInfo" TEXT, "Cookies" TEXT, "CookiesExpirationDate" DATETIME);
CREATE UNIQUE INDEX "IX_IndexerStatus_ProviderId" ON "IndexerStatus" ("ProviderId" ASC);
CREATE TABLE "MetadataFiles" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "MovieId" INTEGER NOT NULL, "Consumer" TEXT NOT NULL, "Type" INTEGER NOT NULL, "RelativePath" TEXT NOT NULL, "LastUpdated" DATETIME NOT NULL, "MovieFileId" INTEGER, "Hash" TEXT, "Added" DATETIME, "Extension" TEXT NOT NULL);
CREATE TABLE "MovieFiles" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "MovieId" INTEGER NOT NULL, "Quality" TEXT NOT NULL, "Size" INTEGER NOT NULL, "DateAdded" DATETIME NOT NULL, "SceneName" TEXT, "MediaInfo" TEXT, "ReleaseGroup" TEXT, "RelativePath" TEXT, "Edition" TEXT, "Languages" TEXT NOT NULL, "IndexerFlags" INTEGER NOT NULL, "OriginalFilePath" TEXT);
CREATE INDEX "IX_MovieFiles_MovieId" ON "MovieFiles" ("MovieId" ASC);
CREATE TABLE "MovieMetadata" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "TmdbId" INTEGER NOT NULL, "ImdbId" TEXT, "Images" TEXT NOT NULL, "Genres" TEXT, "Title" TEXT NOT NULL, "SortTitle" TEXT, "CleanTitle" TEXT, "OriginalTitle" TEXT, "CleanOriginalTitle" TEXT, "OriginalLanguage" INTEGER NOT NULL, "Status" INTEGER NOT NULL, "LastInfoSync" DATETIME, "Runtime" INTEGER NOT NULL, "InCinemas" DATETIME, "PhysicalRelease" DATETIME, "DigitalRelease" DATETIME, "Year" INTEGER, "SecondaryYear" INTEGER, "Ratings" TEXT, "Recommendations" TEXT NOT NULL, "Certification" TEXT, "YouTubeTrailerId" TEXT, "Studio" TEXT, "Overview" TEXT, "Website" TEXT, "Popularity" NUMERIC, "CollectionTmdbId" INTEGER, "CollectionTitle" TEXT);
CREATE UNIQUE INDEX "IX_MovieMetadata_TmdbId" ON "MovieMetadata" ("TmdbId" ASC);
CREATE INDEX "IX_MovieMetadata_CleanTitle" ON "MovieMetadata" ("CleanTitle" ASC);
CREATE INDEX "IX_MovieMetadata_CleanOriginalTitle" ON "MovieMetadata" ("CleanOriginalTitle" ASC);
CREATE INDEX "IX_MovieMetadata_CollectionTmdbId" ON "MovieMetadata" ("CollectionTmdbId" ASC);
CREATE TABLE "PendingReleases" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "Title" TEXT NOT NULL, "Added" DATETIME NOT NULL, "Release" TEXT NOT NULL, "MovieId" INTEGER NOT NULL, "ParsedMovieInfo" TEXT, "Reason" INTEGER NOT NULL, "AdditionalInfo" TEXT);
CREATE TABLE "ScheduledTasks" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "TypeName" TEXT NOT NULL, "Interval" NUMERIC NOT NULL, "LastExecution" DATETIME NOT NULL, "LastStartTime" DATETIME);
CREATE UNIQUE INDEX "IX_ScheduledTasks_TypeName" ON "ScheduledTasks" ("TypeName" ASC);
CREATE TABLE "SubtitleFiles" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "MovieId" INTEGER NOT NULL, "MovieFileId" INTEGER NOT NULL, "RelativePath" TEXT NOT NULL, "Extension" TEXT NOT NULL, "Added" DATETIME NOT NULL, "LastUpdated" DATETIME NOT NULL, "Language" INTEGER NOT NULL, "LanguageTags" TEXT, "Title" TEXT, "Copy" INTEGER NOT NULL DEFAULT 0);
CREATE TABLE "VersionInfo" ("Version" INTEGER NOT NULL, "AppliedOn" DATETIME, "Description" TEXT);
CREATE UNIQUE INDEX "UC_Version" ON "VersionInfo" ("Version" ASC);
CREATE TABLE "AlternativeTitles" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "Title" TEXT NOT NULL, "CleanTitle" TEXT NOT NULL, "SourceType" INTEGER NOT NULL, "MovieMetadataId" INTEGER NOT NULL);
CREATE INDEX "IX_AlternativeTitles_CleanTitle" ON "AlternativeTitles" ("CleanTitle" ASC);
CREATE INDEX "IX_AlternativeTitles_MovieMetadataId" ON "AlternativeTitles" ("MovieMetadataId" ASC);
CREATE TABLE "ImportListStatus" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "ProviderId" INTEGER NOT NULL, "InitialFailure" DATETIME, "MostRecentFailure" DATETIME, "EscalationLevel" INTEGER NOT NULL, "DisabledTill" DATETIME, "LastInfoSync" DATETIME);
CREATE UNIQUE INDEX "IX_NetImportStatus_ProviderId" ON "ImportListStatus" ("ProviderId" ASC);
CREATE TABLE "AutoTagging" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "Name" TEXT NOT NULL, "Specifications" TEXT NOT NULL DEFAULT '[]', "RemoveTagsAutomatically" INTEGER NOT NULL DEFAULT 0, "Tags" TEXT NOT NULL DEFAULT '[]');
CREATE UNIQUE INDEX "IX_AutoTagging_Name" ON "AutoTagging" ("Name" ASC);
CREATE TABLE "ReleaseProfiles" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "Required" TEXT, "Ignored" TEXT, "Tags" TEXT NOT NULL, "Name" TEXT, "Enabled" INTEGER NOT NULL, "IndexerId" INTEGER NOT NULL);
CREATE TABLE "Movies" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "Path" TEXT NOT NULL, "Monitored" INTEGER NOT NULL, "QualityProfileId" INTEGER NOT NULL, "Added" DATETIME, "Tags" TEXT, "AddOptions" TEXT, "MovieFileId" INTEGER NOT NULL, "MinimumAvailability" INTEGER NOT NULL, "MovieMetadataId" INTEGER NOT NULL, "LastSearchTime" DATETIME);
CREATE UNIQUE INDEX "IX_Movies_MovieMetadataId" ON "Movies" ("MovieMetadataId" ASC);
CREATE TABLE "ImportLists" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "Enabled" INTEGER NOT NULL, "Name" TEXT NOT NULL, "Implementation" TEXT NOT NULL, "ConfigContract" TEXT, "Settings" TEXT, "EnableAuto" INTEGER NOT NULL, "RootFolderPath" TEXT NOT NULL, "QualityProfileId" INTEGER NOT NULL, "MinimumAvailability" INTEGER NOT NULL, "Tags" TEXT, "SearchOnAdd" INTEGER NOT NULL, "Monitor" INTEGER NOT NULL);
CREATE UNIQUE INDEX "IX_NetImport_Name" ON "ImportLists" ("Name" ASC);
CREATE TABLE "NotificationStatus" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "ProviderId" INTEGER NOT NULL, "InitialFailure" DATETIME, "MostRecentFailure" DATETIME, "EscalationLevel" INTEGER NOT NULL, "DisabledTill" DATETIME);
CREATE UNIQUE INDEX "IX_NotificationStatus_ProviderId" ON "NotificationStatus" ("ProviderId" ASC);
CREATE INDEX "IX_Blocklist_MovieId" ON "Blocklist" ("MovieId" ASC);
CREATE INDEX "IX_Blocklist_Date" ON "Blocklist" ("Date" ASC);
CREATE INDEX "IX_History_MovieId_Date" ON "History" ("MovieId" ASC, "Date" DESC);
CREATE INDEX "IX_History_DownloadId_Date" ON "History" ("DownloadId" ASC, "Date" DESC);
CREATE INDEX "IX_Movies_MovieFileId" ON "Movies" ("MovieFileId" ASC);
CREATE INDEX "IX_Movies_Path" ON "Movies" ("Path" ASC);
CREATE TABLE sqlite_stat1(tbl,idx,stat);
